/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author PhuDX
 */
public class Main extends javax.swing.JFrame {
    private Book palBook;
    private BorrowCard palBorrowCard;
    private Reader palReader;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        palBook = new Book();
        palBorrowCard = new BorrowCard();
        palReader = new Reader();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        panelMain = new javax.swing.JPanel();
        btnBorrowCard = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        btnReader = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemBook = new javax.swing.JMenuItem();
        MenuItemReader = new javax.swing.JMenuItem();
        MenuItemBorrow = new javax.swing.JMenuItem();
        MenuItemCollect = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBorrowCard.setText("Phiếu mượn");
        btnBorrowCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowCardActionPerformed(evt);
            }
        });

        btnBook.setText("Sách");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        btnReader.setText("Độc giả");
        btnReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReaderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addContainerGap(713, Short.MAX_VALUE)
                .addComponent(btnReader, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addComponent(btnBorrowCard, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMainLayout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(531, Short.MAX_VALUE)))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnReader, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btnBorrowCard, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMainLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(206, Short.MAX_VALUE)))
        );

        jMenu1.setText("Chương trình");

        MenuItemBook.setText("Sách");
        MenuItemBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemBookActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemBook);

        MenuItemReader.setText("Đọc giả");
        MenuItemReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemReaderActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemReader);

        MenuItemBorrow.setText("Phiếu mượn");
        MenuItemBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemBorrowActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemBorrow);

        MenuItemCollect.setText("Phiếu thu");
        jMenu1.add(MenuItemCollect);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Chức năng");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        panelMain.setLayout(new FlowLayout());
        panelMain.removeAll();
        panelMain.add(palBook, BorderLayout.CENTER);
        panelMain.updateUI();
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReaderActionPerformed
        // TODO add your handling code here:
        panelMain.setLayout(new FlowLayout());
        panelMain.removeAll();
        panelMain.add(palReader, BorderLayout.CENTER);
        panelMain.updateUI();
    }//GEN-LAST:event_btnReaderActionPerformed

    private void btnBorrowCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowCardActionPerformed
        // TODO add your handling code here:
        panelMain.setLayout(new FlowLayout());
        panelMain.removeAll();
        panelMain.add(palBorrowCard, BorderLayout.CENTER);
        panelMain.updateUI();
    }//GEN-LAST:event_btnBorrowCardActionPerformed

    private void MenuItemBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemBookActionPerformed
        // TODO add your handling code here:
        panelMain.setLayout(new FlowLayout());
        panelMain.removeAll();
        panelMain.add(palBook, BorderLayout.CENTER);
        panelMain.updateUI();
    }//GEN-LAST:event_MenuItemBookActionPerformed

    private void MenuItemReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemReaderActionPerformed
        // TODO add your handling code here:
        panelMain.setLayout(new FlowLayout());
        panelMain.removeAll();
        panelMain.add(palReader, BorderLayout.CENTER);
        panelMain.updateUI();
    }//GEN-LAST:event_MenuItemReaderActionPerformed

    private void MenuItemBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemBorrowActionPerformed
        // TODO add your handling code here:
        panelMain.setLayout(new FlowLayout());
        panelMain.removeAll();
        panelMain.add(palBorrowCard, BorderLayout.CENTER);
        panelMain.updateUI();
    }//GEN-LAST:event_MenuItemBorrowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemBook;
    private javax.swing.JMenuItem MenuItemBorrow;
    private javax.swing.JMenuItem MenuItemCollect;
    private javax.swing.JMenuItem MenuItemReader;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnBorrowCard;
    private javax.swing.JButton btnReader;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
